# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 490d6c9d429300753a46717b63d8f57c07ad262ffd9a74335e0b717b4ebef22a1a57323c653023754c65377d6986c7d88fe3aa66036151ec2cf1fd6fcadecca7

test:
  secret_key_base: 9699fe6e7961527ac687865f9e9066f098554cd484b321f2c524a2a3b9c6eacd5e3144820c840296416a90f0adbddbd3e6d039565bb4b677ee27f33a35f6259f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
